-- 007: Expand dancers with measurements and contact info
ALTER TABLE dancers
  ADD COLUMN IF NOT EXISTS height TEXT,
  ADD COLUMN IF NOT EXISTS weight TEXT,
  ADD COLUMN IF NOT EXISTS bust TEXT,
  ADD COLUMN IF NOT EXISTS waist TEXT,
  ADD COLUMN IF NOT EXISTS hips TEXT,
  ADD COLUMN IF NOT EXISTS inseam TEXT,
  ADD COLUMN IF NOT EXISTS shoe_size TEXT,
  ADD COLUMN IF NOT EXISTS tights_size TEXT,
  ADD COLUMN IF NOT EXISTS headpiece_size TEXT,
  ADD COLUMN IF NOT EXISTS parent_name TEXT,
  ADD COLUMN IF NOT EXISTS parent_email TEXT,
  ADD COLUMN IF NOT EXISTS parent_phone TEXT,
  ADD COLUMN IF NOT EXISTS notes TEXT NOT NULL DEFAULT '';
